apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: shell-operator:monitor-pods
    imagePullPolicy: Always
  serviceAccountName: monitor-pods-acc