apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    labels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      clusterctl.cluster.x-k8s.io: ""
      control-plane: controller-manager
    name: capi-kubeadm-control-plane-controller-manager
    namespace: capi-kubeadm-control-plane-system
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        cluster.x-k8s.io/provider: control-plane-kubeadm
        control-plane: controller-manager
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          cluster.x-k8s.io/provider: control-plane-kubeadm
          control-plane: controller-manager
      spec:
        containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - --metrics-addr=127.0.0.1:8080
          - --enable-leader-election
          command:
          - /manager
          image: us.gcr.io/k8s-artifacts-prod/cluster-api/kubeadm-control-plane-controller:v0.3.6
          imagePullPolicy: IfNotPresent
          name: manager
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 10
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      clusterctl.cluster.x-k8s.io: ""
      control-plane: controller-manager
    name: capi-kubeadm-control-plane-controller-manager-metrics-service
    namespace: capi-kubeadm-control-plane-system
  spec:
    clusterIP: 10.96.0.220
    ports:
    - name: https
      port: 8443
      targetPort: https
    selector:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      control-plane: controller-manager
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      clusterctl.cluster.x-k8s.io: ""
    name: capi-kubeadm-control-plane-leader-election-role
    namespace: capi-kubeadm-control-plane-system
  rules:
  - resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - resources:
    - configmaps/status
    verbs:
    - get
    - update
    - patch
  - resources:
    - events
    verbs:
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      clusterctl.cluster.x-k8s.io: ""
    name: capi-kubeadm-control-plane-manager-role
    namespace: capi-kubeadm-control-plane-system
  rules:
  - resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - watch
  - apiGroups:
    - rbac
    resources:
    - rolebindings
    verbs:
    - create
    - get
    - list
    - watch
  - apiGroups:
    - rbac
    resources:
    - roles
    verbs:
    - create
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      clusterctl.cluster.x-k8s.io: ""
    name: capi-kubeadm-control-plane-leader-election-rolebinding
    namespace: capi-kubeadm-control-plane-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: capi-kubeadm-control-plane-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: capi-kubeadm-control-plane-system
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

