---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: saada/shell-operator:secret-copier
    imagePullPolicy: Always
  serviceAccountName: secret-copier-acc
