apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      fluxcd.io/sync-checksum: 6692367a51701d9ae599b24d0b6239c61764b486
    labels:
      cluster.x-k8s.io/provider: infrastructure-aws
      clusterctl.cluster.x-k8s.io: ""
      control-plane: capa-controller-manager
      fluxcd.io/sync-gc-mark: sha256.-_k-YkdmQ6P9pWqSumPauDrwl8mP6Rwy19Hxqe-1hD0
    name: capa-controller-manager
    namespace: capa-system
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        cluster.x-k8s.io/provider: infrastructure-aws
        control-plane: capa-controller-manager
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          cluster.x-k8s.io/provider: infrastructure-aws
          control-plane: capa-controller-manager
      spec:
        containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - --metrics-addr=127.0.0.1:8080
          - --enable-leader-election
          env:
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /home/.aws/credentials
          image: us.gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller:v0.5.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
          - containerPort: 9440
            name: healthz
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: healthz
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /home/.aws
            name: credentials
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 10
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        volumes:
        - name: credentials
          secret:
            defaultMode: 420
            secretName: capa-manager-bootstrap-credentials
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fluxcd.io/sync-checksum: 2ee018ba70823127007ea55950e29f9c8f16a780
      prometheus.io/port: "8443"
      prometheus.io/scheme: https
      prometheus.io/scrape: "true"
    labels:
      cluster.x-k8s.io/provider: infrastructure-aws
      clusterctl.cluster.x-k8s.io: ""
      control-plane: capa-controller-manager
      fluxcd.io/sync-gc-mark: sha256.97l90OHLP9M9mWRVvVstkT-LDy3Fnu0ju3rMRdJyaog
    name: capa-controller-manager-metrics-service
    namespace: capa-system
  spec:
    clusterIP: 10.102.119.83
    ports:
    - name: https
      port: 8443
      targetPort: https
    selector:
      cluster.x-k8s.io/provider: infrastructure-aws
      control-plane: capa-controller-manager
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      cluster.x-k8s.io/provider: infrastructure-aws
      clusterctl.cluster.x-k8s.io: ""
    name: capa-leader-election-role
    namespace: capa-system
  rules:
  - resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - resources:
    - configmaps/status
    verbs:
    - get
    - update
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      fluxcd.io/sync-checksum: d9b0ebb3756870341a902d0c85737cc0a8627817
    labels:
      cluster.x-k8s.io/provider: infrastructure-aws
      clusterctl.cluster.x-k8s.io: ""
      fluxcd.io/sync-gc-mark: sha256.hb3Ynd-AvMCCGSWyE1pSC63F6D1N-n1CfjmRcnd9WLk
    name: capa-leader-election-rolebinding
    namespace: capa-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: capa-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: capa-system
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

