apiVersion: v1
items:
- apiVersion: cert-manager.io/v1alpha2
  kind: Issuer
  metadata:
    labels:
      cluster.x-k8s.io/provider: infrastructure-aws
      clusterctl.cluster.x-k8s.io: ""
      clusterctl.cluster.x-k8s.io/lifecycle: shared
    name: capa-selfsigned-issuer
    namespace: capi-webhook-system
- apiVersion: cert-manager.io/v1alpha2
  kind: Issuer
  metadata:
    labels:
      cluster.x-k8s.io/provider: bootstrap-kubeadm
      clusterctl.cluster.x-k8s.io: ""
      clusterctl.cluster.x-k8s.io/lifecycle: shared
    name: capi-kubeadm-bootstrap-selfsigned-issuer
    namespace: capi-webhook-system
- apiVersion: cert-manager.io/v1alpha2
  kind: Issuer
  metadata:
    labels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      clusterctl.cluster.x-k8s.io: ""
      clusterctl.cluster.x-k8s.io/lifecycle: shared
    name: capi-kubeadm-control-plane-selfsigned-issuer
    namespace: capi-webhook-system
- apiVersion: cert-manager.io/v1alpha2
  kind: Issuer
  metadata:
    labels:
      cluster.x-k8s.io/provider: cluster-api
      clusterctl.cluster.x-k8s.io: ""
      clusterctl.cluster.x-k8s.io/lifecycle: shared
    name: capi-selfsigned-issuer
    namespace: capi-webhook-system
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

